[target.thumbv7em-none-eabihf]
runner = "probe-run --chip nRF52840_xxAA"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf" # = ARM Cortex-M4

[env]
DEFMT_LOG="info"
